---
title: "Startsitzung"
author: Pascal Gitz
date: 09/20/2023
date-format: full
chalkboard: True
---

# Aufgabenstellung
## Ziel
*In den Vertiefungsarbeiten und der Masterarbeit soll mit analytischen und numerischen Methoden das Tragverhalten von Stahlbetontragstrukturen auf Grundlage von Versuchen untersucht und verglichen werden.*

## Vorgehen
*Aufarbeitung der Grundlagen von analytischen und numerischen Methoden zur Bestimmung des nichtlinearen Verformungsverhalten von Stahlbeton. Vergleich mit bereits durchgeführten, gut dokumentieren Versuchen.*


# Verformungsverhalten


## Zuggurtmodell

- Beim Reissen des Betons entstehen Risse. Der Rissabstand kann mittels einer Gleichung eingegrenzt werden.
- Die Verbundschubspannung kann anhand einer Verbundschubspannungs-Schlupfbeziehung ermittelt werden. 
- Bei weiterer Laststeigerung beginnt der Betonstahl im Riss zu fliessen.

Das Zuggurtmodell berücksichtigt eine Verbundwirkung im ungerissenen Beton.



## Biegeverformungen

- Aufgrund eines Momenten-Krümmungsdiagramms können Biegeverformungen bestimmt werden.
- Es gilt zwischen einer gerissenen und einer ungerissenen Biegesteifigkeit zu unterscheiden. Diese können leicht an einem Querschnitt ermittelt werden.
- Wie erwähnt, berücksichtigt das Zuggurtmodell eine Verbundschubspannung im Rissbereich (zwischen zwei Rissen). Dies wird folgend als Zugversteifung bezeichnet.
- Marti hat einen Ansatz um die Zugversteifung bei Biegeverformungen zu berücksichtigen. Dabei wird eine Krümmungsdifferenz ermittelt. Diese ist belastungsunabhängig und folglich eine Vereinfachung.


## Fragen

- Was ist der Input und was ist der Output des Zuggurtmodells?
- Muss man sich auf Biegeverformungen beschränken (oder allenfalls Längsdehnungen Zug)?


## Mohrsche Analogie

- Wird bei einem Biegeträger die Momentenlinie zwei mal abgeleitet, so erhält man die Belastung. Dazu gilt, wird die Deformation zwei mal abgeleitet, so erhält man die Momentenlinie geteilt durch die Biegesteifigkeit.

$$
\frac{d^2M}{dx^2} = M'' = -q_z
$$

$$
\frac{d^2w}{dx^2} = w'' = -\frac{M}{EI}
$$

# Abgrenzung


