# Einleitung 

Bei der Analyse des Tragverhaltens ist die Bestimmung von Verformungen im Stahlbetonbau in der Praxis oftmals mit Unsicherheiten verbunden. Die vorwiegend aus Biegung resultierenden Verformungen werden vereinfacht unter der Annahme einer konstanten Biegesteifigkeit berechnet. Diese wird grundsätzlich am gerissenen oder am ungerissenen Querschnitt bestimmt. Mit dieser Arbeit sollen die Grenzen dieser Modellvorstellung aufgezeigt werden. Des Weiteren wird versucht, mit einem möglichst pragmatischen Ansatz die eingeschränkte Modellvorstellung zu erweitern und die Verformungen genauer abzubilden. 

Die Arbeit umfasst ein einleitendes Kapitel, welches die Modellvorstellungen in ihren Grundeigenschaften aufgreift und erläutert, gefolgt von zwei Kapiteln, welche die Anwendung der Modellvorstellungen aufzeigen. Es wird ein Dreipunktbiegeversuch aus dem Versuchsbericht @Jaeger2006, sowie ein Vierpunktbiegeversuch aus dem Versuchsbericht @Tue2019 analysiert. Es werden ausschliesslich Stabtragwerke betrachtet. Das Berechnungsvorgehen ist für beide Versuche analog zueinander. Die Kapitel werden mit einem Vergleich der Modellvorstellungen abgeschlossen. Der Schlusspunkt der Arbeit liefert ein Fazit, welches die Erkenntnisse der Berechnungen erneut aufgreift, zusammenfasst und interpretiert.

Abschliessend lässt sich festhalten, dass diese Arbeit das grundlegende Verständnis der Verformungen im Stahlbetonbau schärfen soll. Dazu sollen Methoden aufgezeigt werden, durch welche    sich die Verformungen rechnerisch ermitteln lassen. Stets im Sinne der praktischen Anwendung.