# Gebrauchstauglichkeit

Folgend werden die wichtigsten Grundsätze nach @Spathelf2022 in eigenen Worten beschrieben.

## Zuggurtmodell

Das Zuggurtmodell beschreibt das Spannungsdehnungs-Verhalten eines Beton-Betonstahl Verbundquerschnitts. Folgende Verhaltenswerte sind ausschlaggebend:

- Der Verbund verhält sich bis zum Reissen des Betons linear elastisch.
- Beim Reissen des Betons entstehen Risse. Der Rissabstand kann mittels einer Gleichung eingegrenzt werden.
- Im Riss ist der Beton Spannungsfrei.
- Zwischen den Rissen herrscht ein Gleichgewicht zwischen Betonstahlspannung und Verbundschubspannung, sowie der Einwirkung. 
- Die Verbundschubspannung kann anhand einer Verbundschubspannungs-Schlupfbeziehung ermittelt werden. Dabei gilt, der Schlupf ist bei den Rissen maximal und führt zu null in der Mitte des Rissbereichs.
- Bei weiterer Laststeigerung beginnt der Betonstahl im Riss zu fliessen.
- Durch das Fliessen des Stahls entstehen weitere Risse. Sowie gilt beim Fliessen, dass sich die Verbundschubspannung reduziert. Durch die Reduktion der Verbundschubspannung erhöht sich die Stahlspannung im Bereich, welcher noch nicht fliesst (vom Riss richtung Zentrum des Rissbereichs).
- Aus dem Modell lassen sich mittlere Dehnungen ermitteln, welche ein Mass für die Rissbreiten geben.

Allgemein gilt es Schwinddehnungen zu berücksichtigigen.


## Biegeverformungen

- Aufgrund eines Momenten-Krümmungsdiagramms können Biegeverformungen bestimmt werden.
- Es gilt zwischen einer gerissenen und einer ungerissenen Biegesteifigkeit zu unterscheiden. Diese können leicht an einem Querschnitt ermittelt werden.
- Wie erwähnt, berücksichtigt das Zuggurtmodell eine Verbundschubspannung im Rissbereich (zwischen zwei Rissen). Dies wird folgend als Zugversteifung bezeichnet.
- Marti hat einen Ansatz um die Zugversteifung bei Biegeverformungen zu berücksichtigen. Dabei wird eine Krümmungsdifferenz ermittelt. Diese ist Belastungsunabhängig und folglich eine Vereinfachung.


## Mohrsche Analogie

- Wird bei einem Biegeträger die Momentenlinie zwei mal abgeleitet, so erhält man die Belastung. Dazu gilt, wird die Deformation zwei mal abgeleitet, so erhält man die Momentenlinie geteilt durch die Biegesteifigkeit.

$$
\frac{d^2M}{dx^2} = M'' = -q_z
$$

$$
\frac{d^2w}{dx^2} = w'' = -\frac{M}{EI}
$$

- Die Biegelinien sind für geübte Studenten einfach zu bestimmen. Die Analogie besteht in der zweimaligen Ableitung. Wird nun die Biegelinie als Einwirkung auf das System gegeben, kann daraus die Verformungslinie bestimmt werden. 
- Es gilt das System mit entsprechenden Randbedingungen zu erstellen, dazu gibt es eine Tabelle für Auflager im analogen System (Analogieträger).